-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 15:25:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema baby_happy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema baby_happy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baby_happy` DEFAULT CHARACTER SET utf8 ;
USE `baby_happy` ;

-- -----------------------------------------------------
-- Table `baby_happy`.`profiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL,
  `file` BLOB NULL,
  `external_uri` CHAR(36) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NULL,
  `password` VARCHAR(200) NULL,
  `cpf` VARCHAR(15) NULL,
  `phone` VARCHAR(45) NULL,
  `fk_photo` INT NULL,
  `fk_profile` INT NULL,
  `token` VARCHAR(45) NULL,
  `last_login` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profiles1_idx` (`fk_profile` ASC) VISIBLE,
  INDEX `fk_photo1_idx` (`fk_photo` ASC) VISIBLE,
  CONSTRAINT `fk_profiles1`
    FOREIGN KEY (`fk_profile`)
    REFERENCES `baby_happy`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo1`
    FOREIGN KEY (`fk_photo`)
    REFERENCES `baby_happy`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NULL,
  `description` TEXT NULL,
  `price` FLOAT NULL,
  `discount` INT NULL,
  `status` CHAR(5) NULL COMMENT 'status A= active\n           I = inactive\n',
  `units` INT NULL,
  `fk_category` INT NULL,
  `external_uri` CHAR(36) NULL,
  `datetime_create` DATETIME NULL,
  `datetime_modify` DATETIME NULL,
  `fk_last_user_modify` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_modify_idx` (`fk_last_user_modify` ASC) VISIBLE,
  CONSTRAINT `fk_user_modify`
    FOREIGN KEY (`fk_last_user_modify`)
    REFERENCES `baby_happy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`product_nn_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`product_nn_tag` (
  `fk_product` INT NOT NULL,
  `fk_tag` INT NOT NULL,
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  INDEX `fk_tag_idx` (`fk_tag` ASC) VISIBLE,
  CONSTRAINT `fk_product`
    FOREIGN KEY (`fk_product`)
    REFERENCES `baby_happy`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag`
    FOREIGN KEY (`fk_tag`)
    REFERENCES `baby_happy`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`billboard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`billboard` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_image` INT NULL,
  `uri` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_files_idx` (`fk_image` ASC) VISIBLE,
  CONSTRAINT `fk_files`
    FOREIGN KEY (`fk_image`)
    REFERENCES `baby_happy`.`files` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`user_addreess`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`user_addreess` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NULL,
  `street` VARCHAR(200) NULL,
  `number` VARCHAR(15) NULL,
  `district` VARCHAR(200) NULL,
  `zipcode` VARCHAR(45) NULL,
  `complement` VARCHAR(200) NULL,
  `fk_user` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user1_idx` (`fk_user` ASC) VISIBLE,
  CONSTRAINT `fk_user1`
    FOREIGN KEY (`fk_user`)
    REFERENCES `baby_happy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`coupons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(100) NULL,
  `datetime_expiration` DATETIME NULL,
  `type` CHAR(5) NULL COMMENT 'Type = P = percentage\n            V = Value',
  `amount` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` CHAR(36) NULL,
  `datetime_purchase` DATETIME NULL,
  `datetime_confirm` DATETIME NULL,
  `datetime_shipping` DATETIME NULL,
  `datetime_delivered` DATETIME NULL,
  `datetime_cancel` DATETIME NULL,
  `value` FLOAT NULL,
  `fk_coupon` INT NULL,
  `fk_customer` INT NULL,
  `fk_user_confirm` INT NULL,
  `fk_address` INT NULL,
  `shipping_value` FLOAT NULL,
  `shipping_code` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_idx` (`fk_customer` ASC) VISIBLE,
  INDEX `fk_address_idx` (`fk_address` ASC) VISIBLE,
  INDEX `fk_user_confirm_idx` (`fk_user_confirm` ASC) VISIBLE,
  INDEX `fk_coupon_idx` (`fk_coupon` ASC) VISIBLE,
  CONSTRAINT `fk_customer`
    FOREIGN KEY (`fk_customer`)
    REFERENCES `baby_happy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_address`
    FOREIGN KEY (`fk_address`)
    REFERENCES `baby_happy`.`user_addreess` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_confirm`
    FOREIGN KEY (`fk_user_confirm`)
    REFERENCES `baby_happy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_coupon`
    FOREIGN KEY (`fk_coupon`)
    REFERENCES `baby_happy`.`coupons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`order_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`order_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_order` INT NULL,
  `fk_product` INT NULL,
  `value` FLOAT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_idx` (`fk_order` ASC) VISIBLE,
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  CONSTRAINT `fk_order1`
    FOREIGN KEY (`fk_order`)
    REFERENCES `baby_happy`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product1`
    FOREIGN KEY (`fk_product`)
    REFERENCES `baby_happy`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`notification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fk_order` INT NULL,
  `fk_user` INT NULL,
  `status` CHAR(5) NULL,
  `type` CHAR(5) NULL,
  `read` CHAR(5) NULL COMMENT 'if notification is readed or not. Boolean.',
  PRIMARY KEY (`id`),
  INDEX `fk_order_idx` (`fk_order` ASC) VISIBLE,
  INDEX `fk_user_idx` (`fk_user` ASC) VISIBLE,
  CONSTRAINT `fk_order2`
    FOREIGN KEY (`fk_order`)
    REFERENCES `baby_happy`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user2`
    FOREIGN KEY (`fk_user`)
    REFERENCES `baby_happy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baby_happy`.`wishlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baby_happy`.`wishlist` (
  `fk_user` INT NULL,
  `fk_product` INT NULL,
  INDEX `fk_user_idx` (`fk_user` ASC) VISIBLE,
  INDEX `fk_product_idx` (`fk_product` ASC) VISIBLE,
  CONSTRAINT `fk_user3`
    FOREIGN KEY (`fk_user`)
    REFERENCES `baby_happy`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product3`
    FOREIGN KEY (`fk_product`)
    REFERENCES `baby_happy`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
